[package]
name = "tftools"
version = "0.1.0"
authors = ["Bertrand \"Kamek\" Bousquet <b.kamek@gmail.com>"]
edition = "2018"

[dependencies]
protobuf = "2.12.0"

[build-dependencies]
protoc-rust = "2.12.0"
